### ISSUE TITLE
Include Go instructions as well

### ISSUE THREAD

**Issue by k4rtik** [nicolashery/mac-dev-setup#15]
1. $ `brew install go`
2. Setup GOPATH to $HOME/Projects/go
3. Include $GOPATH/bin in PATH
4. Optionally do a `brew install mercurial`

Ref: [How to Write Go code](http://golang.org/doc/code.html)

**Comment by nicolashery** [comment]
Thanks for the suggestion! I don't use Go personally, and I try to keep this guide short and simple so include only a couple programming languages
