### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by sotoer** [nicolashery/mac-dev-setup#21]
I think this is a must for node dev https://github.com/creationix/nvm

**Comment by nicolashery** [comment]
Thanks, I agree! I'm working on version `2.0` of this doc, and have added `nvm`: https://github.com/nicolashery/mac-dev-setup/tree/2.0#nodejs

**Comment by thegauravtiwari** [comment]
is this included in readme.md ?

**Comment by nicolashery** [comment]
Thanks again for the suggestion. I included `nvm` in the latest version of this guide.
