### ISSUE TITLE
/usr/local/share/python no longer needed in PATH

### ISSUE THREAD

**Issue by k4rtik** [nicolashery/mac-dev-setup#22]
See: https://github.com/Homebrew/homebrew/commit/49d04cb5b7fbbe8a88e9c4fabe288b7899e4e3e7

This results in an unnecessary warning in `brew doctor`:

```
Warning: /usr/local/share/python is not needed in PATH.
```

So, in **Python** section, the following needs some revision:

```
Executable scripts from Python packages you install will be put in /usr/local/share/python, so let's add it to the $PATH. To do so, we'll create a .path text file in the home directory (I've already set up .bash_profile to call this file):

$ cd ~
$ subl .path
And add these lines to .path:

PATH=/usr/local/share/python:$PATH
export PATH
Save the file and open a new terminal to take the new $PATH into account (everytime you open a terminal, .bash_profile gets loaded).
```

**Comment by mukeshtiwari1987** [comment]
I removed the following lines from under .path

PATH=/usr/local/share/python:$PATH
export PATH

Restarted terminal and no warnings were received.

**Comment by k4rtik** [comment]
@mukeshtiwari1987 this repo seems unmaintained, I usually go to its fork at https://github.com/jfrazelle/mac-dev-setup whenever I need to setup a new Mac or refer something in the configuration.

**Comment by mukeshtiwari1987** [comment]
Search mac os dev set up and https://github.com/nicolashery/mac-dev-setup is the first link. what can be done?

**Comment by nicolashery** [comment]
Thanks for pointing this out! I'm working on `v2.0` of this doc (https://github.com/nicolashery/mac-dev-setup/tree/2.0), and will make sure to fix the Python section with your recommendation.

**Comment by nicolashery** [comment]
I pushed an update to this guide, and I now explain how to install Python via `pyenv`, so that should fix this issue.
