### ISSUE TITLE
numpy and scipy installation issues

### ISSUE THREAD

**Issue by dduugg** [nicolashery/mac-dev-setup#25]
I think the preferred way to install numpy and scipy is now via Homebrew's own Python [formulae](https://github.com/Homebrew/homebrew-python):

```
$ brew install homebrew/python/numpy
$ brew install homebrew/python/scipy
```

It's no longer necessary install `gcc` either (and doing so will lead to the issue described [here](https://github.com/Homebrew/homebrew/issues/31156)). Happy to submit a PR if you agree.

**Comment by Rabscuttler** [comment]
On 2.8GHz macbook it took me ~43 minutes to install `gcc`. 

There are some questions around the internet from people worrying about the long install time, and some not even waiting for the build, so it might be useful to add to the warning if you keep it in.

**Comment by nicolashery** [comment]
Thanks for raising the issue. I updated the guide https://github.com/nicolashery/mac-dev-setup/commit/bffbe4b741052d6122a6f690d9fb2b5172130a2a, and I now explain how to install an Anaconda/Miniconda distribution, which makes it easier to install Numpy and Scipy.
