### ISSUE TITLE
Add virtualenv-mgr?

### ISSUE THREAD

**Issue by philippeowagner** [nicolashery/mac-dev-setup#31]
Hi @nicolashery 

Are you interested to list [virtualenv-mgr](https://github.com/arteria/virtualenv-mgr) in your document? virtualenv-mgr was build to manage (diff, update, statistics, find env with packages, ..) multiple envs in parallel. This saves a lot of time for example to upgrade all envs to the latest version of a specific package.

**Comment by nicolashery** [comment]
Thanks for the suggestion. I want to keep this guide simple enough, so I'll leave it at `virtualenv` for now.

**Comment by philippeowagner** [comment]
After 4 years this has no relevance anyways...
