### ISSUE TITLE
Why not add a custom resolution modifier

### ISSUE THREAD

**Issue by eduardosanzb** [nicolashery/mac-dev-setup#35]
I Like to use this app to modify the resolution of the MB
- https://www.reddit.com/r/apple/comments/vi9yf/set_your_retina_macbook_pros_resolution_to/

**Comment by nicolashery** [comment]
Thanks for pointing me to it. I can't include every app out there, and there are a lot of interesting ones :) I'll keep it to a small selection of apps I commonly use...
