### ISSUE TITLE
Mysql_install_db

### ISSUE THREAD

**Issue by jacobwhitten** [nicolashery/mac-dev-setup#40]
--tmpdir appears to no longer be an argument for the mysql_install_db command. This causes the command to fail.

**Comment by audip** [comment]
Use this:  `mysqld -initialize --verbose --user=whoami --basedir="$(brew --prefix mysql)" --datadir=/usr/local/var/mysql --tmpdir=/tmp`
Source : http://stackoverflow.com/questions/34345726/brew-install-mysql-on-mac-os-el-capitan

**Comment by nicolashery** [comment]
Thanks for letting me know. In the latest version of this guide (https://github.com/nicolashery/mac-dev-setup/commit/bffbe4b741052d6122a6f690d9fb2b5172130a2a), I've actually replaced MySQL with PostgreSQL in the installation instructions.
