### ISSUE TITLE
iTerm2 now has Solarized colors built-in

### ISSUE THREAD

**Issue by tedb** [nicolashery/mac-dev-setup#46]
I followed your instructions to download the Solarized color palette for iTerm2, but when I opened iTerm's preferences to import the file, I saw Solarized Dark and Solarized Light are now built-in.  Maybe modify your instructions to remove the step of downloading Solarized?

**Comment by nicolashery** [comment]
I've updated this guide (https://github.com/nicolashery/mac-dev-setup/commit/bffbe4b741052d6122a6f690d9fb2b5172130a2a), and include instructions to install Atom One color schemes. Again, matter of personal preferences, and it will likely change :)
