### ISSUE TITLE
pyqt is not an available formulae in brew taps

### ISSUE THREAD

**Issue by ricreyna** [nicolashery/mac-dev-setup#49]
modify the instruction to:
```brew install pyqt5```

**Comment by nicolashery** [comment]
Thanks for letting me know. I updated the guide (https://github.com/nicolashery/mac-dev-setup/commit/bffbe4b741052d6122a6f690d9fb2b5172130a2a), and now explain how to install Anaconda/Miniconda distributions, which make it easier to install dependencies such as `pyqt`.
