### ISSUE TITLE
Elastic Search has changed

### ISSUE THREAD

**Issue by Hunchmun** [nicolashery/mac-dev-setup#50]
By default, the elastic search plugin program is now called elasticsearch-plugin, 

The install flag is removed in favour of an argument ('install' instead of '--install') 

And the recommended plugin (elasticsearch-plugin --install mobz/elasticsearch-head) no longer exists/installs correctly

Hope this helps!

**Comment by nicolashery** [comment]
Thanks for the heads up! I released a new version of this guide (https://github.com/nicolashery/mac-dev-setup/commit/bffbe4b741052d6122a6f690d9fb2b5172130a2a), and I now point people to **Dejavu** for an Elasticsearch GUI.
