### ISSUE TITLE
2.0 branch has references to "master" branch dotfiles

### ISSUE THREAD

**Issue by denvercoder** [nicolashery/mac-dev-setup#52]
Hey Nicolas,

I don't know if this was intentional or not but in the 2.0 version you have some dotfiles but in the README.md file you have the file paths to the master versions. I know there are some differences. Just wanted to let you know.

If it wasn't intentional I can submit a pull request and fix it for you. I'm trying to contribute more on Github.

**Comment by nicolashery** [comment]
Thanks for pointing that out. The branch was meant to be merged into `master`, which I did in the latest update (https://github.com/nicolashery/mac-dev-setup/commit/bffbe4b741052d6122a6f690d9fb2b5172130a2a). So that should've fixed things.
