### ISSUE TITLE
ipython install produces error under homebrew

### ISSUE THREAD

**Issue by sparr** [nicolashery/mac-dev-setup#60]
ipython[test] depends on ... depends on nose

nose produces an exception and stack trace when pip tries to install it, due to /usr/local/man not existing and /usr/local/ not being writable by the user

I don't think any layer of this problem will want to fix it. The homebrew install devs already said they won't fix homebrew to link /usr/local/man to /usr/local/share/man so that FHS-compliance-expecting pip packages will install cleanly. python and pip aren't doing anything wrong by respecting where nose says it wants to install its man pages. and nose isn't doing anything wrong by trying to install its man pages to a location the FHS says should exist.

You should probably just mention in your ipython section that there is a known exception/error during the process. Or maybe not install the [test] feature?

**Comment by aakent** [comment]
@sparr 
Do you know of any other git repo or step by step that is as details as nicolashery's but up to date?

**Comment by nicolashery** [comment]
Sorry you ran into some issues. I released a new version of this guide, in which I explain how to install Anaconda/Miniconda distributions, which should make it easier to install dependencies such as `ipython`.
