### ISSUE TITLE
"mysql.server start" is "mysql.server: command not found"

### ISSUE THREAD

**Issue by robertandrews** [nicolashery/mac-dev-setup#62]
I followed the instructions to install MySQL: 
`brew install mysql`

... it went through a lot of status reporting on the install...

Then it paused for a while on ...
```
==> ./bootstrap --prefix=/usr/local/Cellar/cmake/3.11.3 --no-system-libs --parallel=4 --datadir=/share/cmake --docdir=/share/
mysql.server start
```

Then it gave me back my command line.

But, when I test out with `mysql.server start`, it reports `mysql.server: command not found`

**Comment by thegauravtiwari** [comment]
Try :
` brew services start mysql `

 mysql.server start also works.
In case neither of them work, try reinstalling mysql using homebrew

**Comment by nicolashery** [comment]
Indeed, in a new version of the guide (https://github.com/nicolashery/mac-dev-setup/commit/bffbe4b741052d6122a6f690d9fb2b5172130a2a), I now suggest using `brew services start <service>` to start/stop databases such as MySQL.
