### ISSUE TITLE
[Suggestion] Replace Marked with MacDown

### ISSUE THREAD

**Issue by ronakdev** [nicolashery/mac-dev-setup#63]
[MacDown](https://macdown.uranusjr.com/): MacDown allows you to edit Markdown with live rendering, custom styling (Github rendering supported), and is super fast. **100% Free**

**Comment by nicolashery** [comment]
Thanks for the suggestion! In the latest version of the guide, I actually removed Marked. I personally use Visual Studio Code, which has a decent Markdown editing and live preview experience I find.
