### ISSUE TITLE
virtualenv --distribute option is deprecated

### ISSUE THREAD

**Issue by WilliamYuhangLee** [nicolashery/mac-dev-setup#68]
In the [**Virtualenv**](https://github.com/nicolashery/mac-dev-setup#virtualenv) section, the option "--distribute" has gone obsolete and has no real effect as for version 16.3.0. See [source code in virtualenv.py](https://github.com/pypa/virtualenv/blob/5016707a064745da3e4fdbd72edc534838862c96/virtualenv.py#L754).

**Comment by nicolashery** [comment]
Thanks for the heads up. In the latest version of the guide, this option no longer appears.
