### ISSUE TITLE
Add a browsers section

### ISSUE THREAD

**Issue by audip** [nicolashery/mac-dev-setup#69]
This is a great alternative to Chrome with a focus on privacy and in this dev setup we should let folks choose between the Chromium browser of their choice: [Google Chrome](https://www.google.com/chrome/) or [Brave](https://brave.com/)

**Comment by nicolashery** [comment]
Hum, as I state in the introduction, I don't want to include too many options to keep the guide simple. The guide is opinionated on purpose.

That said, Google Chrome is not necessary for the rest of the setup (the Developer Tools are useful if you're a web developer). And installing one's favorite browser is usually trivial, so I may actually remove this section altogether.

**Comment by nicolashery** [comment]
Removed browser section in https://github.com/nicolashery/mac-dev-setup/commit/eeb44c1d9f9971ccd0d70b42abbd206bcaf2d84a
